# SITE CONFIG
title: AlunosMaio
description: Tudo em um sรณ lugar.
org_title: Raincorn

#SITE SETTINGS
exclude: [vendor]
css_url: http://127.0.0.1:4000/assets/css/
github_repository: https://github.com/raincorn/alunosmaio
domain: http://127.0.0.1:4000/
org_url: https://raincorn.github.io/
current_version: v2.1.3-beta.1
git_repo: true
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
